"""empty message

Revision ID: 0ef83f491beb
Revises: 00bffcd00ec2
Create Date: 2025-11-05 13:51:35.712064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ef83f491beb'
down_revision = '00bffcd00ec2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create', sa.Date(), nullable=True))
        batch_op.drop_column('date')

    with op.batch_alter_table('invoice_detail', schema=None) as batch_op:
        batch_op.add_column(sa.Column('crete_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice_detail', schema=None) as batch_op:
        batch_op.drop_column('crete_at')

    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DATE(), nullable=True))
        batch_op.drop_column('create')

    # ### end Alembic commands ###
