"""empty message

Revision ID: 4c8af49633a0
Revises: a67218ec244a
Create Date: 2025-11-05 13:54:23.759547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c8af49633a0'
down_revision = 'a67218ec244a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice_detail', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('crete_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice_detail', schema=None) as batch_op:
        batch_op.add_column(sa.Column('crete_at', sa.DATETIME(), nullable=True))
        batch_op.drop_column('create_at')

    # ### end Alembic commands ###
