"""empty message

Revision ID: a67218ec244a
Revises: 0ef83f491beb
Create Date: 2025-11-05 13:52:01.550363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a67218ec244a'
down_revision = '0ef83f491beb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_at', sa.Date(), nullable=True))
        batch_op.drop_column('create')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create', sa.DATE(), nullable=True))
        batch_op.drop_column('create_at')

    # ### end Alembic commands ###
