"""empty message

Revision ID: c2c8d1bc08b1
Revises: e3a08cee7dd4
Create Date: 2025-11-05 23:40:33.928687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2c8d1bc08b1'
down_revision = 'e3a08cee7dd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_at', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('create_at')

    # ### end Alembic commands ###
