"""empty message

Revision ID: e1964f17e69b
Revises: 4c8af49633a0
Create Date: 2025-11-05 15:02:14.748031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1964f17e69b'
down_revision = '4c8af49633a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_type', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('criteria_type', sa.String(length=20), nullable=True),
    sa.Column('criteria_id', sa.Integer(), nullable=True),
    sa.Column('criteria_name', sa.String(length=100), nullable=True),
    sa.Column('total_sales', sa.Float(), nullable=False),
    sa.Column('total_qty', sa.Integer(), nullable=False),
    sa.Column('total_invoices', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sales_report')
    # ### end Alembic commands ###
