"""empty message

Revision ID: ef7bbb838ed7
Revises: c2c8d1bc08b1
Create Date: 2025-11-06 12:47:46.733843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef7bbb838ed7'
down_revision = 'c2c8d1bc08b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('create_at')

    # ### end Alembic commands ###
